using System.Linq;
using FluentAssertions;
using Spectacle.Gate;
using Xunit;

namespace Spectacle.Tests;

public class FrontMatterTests
{
    [Fact]
    public void Absent_when_the_document_does_not_open_with_a_fence()
    {
        FrontMatter.Parse("# Title\n\nText.\n").Present.Should().BeFalse();
        FrontMatter.Parse("").Present.Should().BeFalse();
        FrontMatter.Parse(null).Present.Should().BeFalse();
    }

    [Fact]
    public void Absent_when_a_blank_line_precedes_the_fence()
    {
        // Every parser requires the fence on line 1, so a header pushed down by a blank line is
        // not front matter — treating it as one would disagree with the rest of the toolchain.
        FrontMatter.Parse("\n---\ntitle: Draft\n---\n").Present.Should().BeFalse();
    }

    [Fact]
    public void Parses_scalar_keys_with_their_lines()
    {
        var header = FrontMatter.Parse("---\ntitle: Auth design\nstatus: draft\n---\n\n# Auth\n");

        header.Present.Should().BeTrue();
        header.Closed.Should().BeTrue();
        header.StartLine.Should().Be(1);
        header.EndLine.Should().Be(4);
        header.Entries.Select(e => e.Key).Should().Equal("title", "status");
        header.Find("title")!.Value.Should().Be("Auth design");
        header.Find("title")!.Line.Should().Be(2);
        header.Find("status")!.Line.Should().Be(3);
    }

    [Fact]
    public void Finds_keys_case_insensitively()
    {
        var header = FrontMatter.Parse("---\nTitle: Auth\n---\n");

        header.Find("title").Should().NotBeNull();
        header.Find("  TITLE  ").Should().NotBeNull();
        header.Find("missing").Should().BeNull();
    }

    [Fact]
    public void Strips_matching_quotes_from_a_scalar()
    {
        var header = FrontMatter.Parse("---\ntitle: \"Auth: design\"\nagent: 'writer'\n---\n");

        header.Find("title")!.Value.Should().Be("Auth: design");
        header.Find("agent")!.Value.Should().Be("writer");
    }

    [Fact]
    public void Parses_a_block_sequence()
    {
        var header = FrontMatter.Parse("---\ntags:\n  - auth\n  - security\n---\n");

        var tags = header.Find("tags")!;
        tags.Items.Should().Equal("auth", "security");
        tags.IsList.Should().BeTrue();
        tags.HasValue.Should().BeTrue();
    }

    [Fact]
    public void Parses_a_flow_sequence()
    {
        var header = FrontMatter.Parse("---\ntags: [auth, \"security\"]\n---\n");

        header.Find("tags")!.Items.Should().Equal("auth", "security");
    }

    [Fact]
    public void Flattens_nested_mappings_into_dotted_keys()
    {
        var header = FrontMatter.Parse("---\nrun:\n  model: opus\n  id: 42\n---\n");

        header.Find("run.model")!.Value.Should().Be("opus");
        header.Find("run.id")!.Value.Should().Be("42");
        // The parent holds no value of its own but is not an unfilled field.
        header.Find("run")!.IsMapping.Should().BeTrue();
        header.Find("run")!.HasValue.Should().BeTrue();
    }

    [Fact]
    public void Marks_every_ancestor_of_a_deeply_nested_key_as_a_mapping()
    {
        var header = FrontMatter.Parse("---\nrun:\n  tool:\n    name: spectacle\n---\n");

        header.Find("run.tool.name")!.Value.Should().Be("spectacle");
        header.Find("run.tool")!.IsMapping.Should().BeTrue();
        header.Find("run")!.IsMapping.Should().BeTrue();
    }

    [Fact]
    public void A_blank_value_is_not_a_filled_in_key()
    {
        var header = FrontMatter.Parse("---\nstatus:\ntitle: Auth\n---\n");

        header.Find("status")!.HasValue.Should().BeFalse();
        header.Find("title")!.HasValue.Should().BeTrue();
    }

    [Fact]
    public void Skips_comments_and_blank_lines()
    {
        var header = FrontMatter.Parse("---\n# generated by the writer agent\n\ntitle: Auth\n---\n");

        header.Entries.Select(e => e.Key).Should().Equal("title");
    }

    [Fact]
    public void Ignores_a_prose_line_that_is_not_a_key()
    {
        // A URL's colon is not followed by whitespace, so it is never read as a key separator.
        var header = FrontMatter.Parse("---\nhttps://example.com/docs\ntitle: Auth\n---\n");

        header.Entries.Select(e => e.Key).Should().Equal("title");
    }

    [Fact]
    public void Reports_an_unclosed_header()
    {
        var header = FrontMatter.Parse("---\ntitle: Auth\n\n# Body\n");

        header.Present.Should().BeTrue();
        header.Closed.Should().BeFalse();
    }

    [Fact]
    public void Closes_on_a_yaml_document_end_marker()
    {
        FrontMatter.Parse("---\ntitle: Auth\n...\n").Closed.Should().BeTrue();
    }

    [Fact]
    public void Tolerates_a_byte_order_mark_before_the_fence()
    {
        FrontMatter.Parse("\uFEFF---\ntitle: Auth\n---\n").Present.Should().BeTrue();
    }

    [Fact]
    public void Metadata_flattens_to_display_pairs_in_source_order()
    {
        var header = FrontMatter.Parse("---\ntitle: Auth\ntags: [a, b]\nrun:\n  model: opus\n---\n");

        header.Metadata.Select(m => m.Key).Should().Equal("title", "tags", "run.model");
        header.Metadata.Select(m => m.Value).Should().Equal("Auth", "a, b", "opus");
    }

    [Fact]
    public void Strip_blanks_the_header_and_preserves_the_line_count()
    {
        const string source = "---\ntitle: Auth\n---\n\n# Body\n\nText.\n";
        var body = FrontMatter.Strip(source);

        body.Split('\n').Length.Should().Be(source.Split('\n').Length);
        body.Split('\n').Take(3).Should().AllSatisfy(l => l.Should().BeEmpty());
        // The body keeps its original line numbers, which is what lets a finding point at the
        // right line of the real file.
        body.Split('\n')[4].Should().Be("# Body");
    }

    [Fact]
    public void Strip_leaves_a_document_without_front_matter_untouched()
    {
        const string source = "# Body\n\nText.\n";
        FrontMatter.Strip(source).Should().Be(source);
    }

    [Fact]
    public void Strip_leaves_an_unclosed_header_untouched()
    {
        // There is no fence to bound, so blanking would swallow the document and hide every other
        // finding; the unclosed header is reported by its own rule instead.
        const string source = "---\ntitle: Auth\n\n# Body\n";
        FrontMatter.Strip(source).Should().Be(source);
    }

    [Fact]
    public void Strip_preserves_crlf_line_endings_in_the_body()
    {
        var body = FrontMatter.Strip("---\r\ntitle: Auth\r\n---\r\n\r\n# Body\r\n");

        body.Should().Contain("# Body\r\n");
    }

    [Fact]
    public void Split_returns_the_header_and_the_body_together()
    {
        var (header, body) = FrontMatter.Split("---\ntitle: Auth\n---\n\n# Body\n");

        header.Find("title")!.Value.Should().Be("Auth");
        body.Should().Contain("# Body").And.NotContain("title: Auth");
    }
}
