using System.Linq;
using FluentAssertions;
using Spectacle.Gate;
using Xunit;

namespace Spectacle.Tests;

public class FrontMatterTests
{
    [Fact]
    public void Absent_when_the_document_does_not_open_with_a_fence()
    {
        FrontMatter.Parse("# Title\n\nText.\n").Present.Should().BeFalse();
        FrontMatter.Parse("").Present.Should().BeFalse();
        FrontMatter.Parse(null).Present.Should().BeFalse();
    }

    [Fact]
    public void Absent_when_a_blank_line_precedes_the_fence()
    {
        // Every parser requires the fence on line 1, so a header pushed down by a blank line is
        // not front matter — treating it as one would disagree with the rest of the toolchain.
        FrontMatter.Parse("\n---\ntitle: Draft\n---\n").Present.Should().BeFalse();
    }

    [Fact]
    public void Parses_scalar_keys_with_their_lines()
    {
        var header = FrontMatter.Parse("---\ntitle: Auth design\nstatus: draft\n---\n\n# Auth\n");

        header.Present.Should().BeTrue();
        header.Closed.Should().BeTrue();
        header.StartLine.Should().Be(1);
        header.EndLine.Should().Be(4);
        header.Entries.Select(e => e.Key).Should().Equal("title", "status");
        header.Find("title")!.Value.Should().Be("Auth design");
        header.Find("title")!.Line.Should().Be(2);
        header.Find("status")!.Line.Should().Be(3);
    }

    [Fact]
    public void Finds_keys_case_insensitively()
    {
        var header = FrontMatter.Parse("---\nTitle: Auth\n---\n");

        header.Find("title").Should().NotBeNull();
        header.Find("  TITLE  ").Should().NotBeNull();
        header.Find("missing").Should().BeNull();
    }

    [Fact]
    public void Strips_matching_quotes_from_a_scalar()
    {
        var header = FrontMatter.Parse("---\ntitle: \"Auth: design\"\nagent: 'writer'\n---\n");

        header.Find("title")!.Value.Should().Be("Auth: design");
        header.Find("agent")!.Value.Should().Be("writer");
    }

    [Fact]
    public void Parses_a_block_sequence()
    {
        var header = FrontMatter.Parse("---\ntags:\n  - auth\n  - security\n---\n");

        var tags = header.Find("tags")!;
        tags.Items.Should().Equal("auth", "security");
        tags.IsList.Should().BeTrue();
        tags.HasValue.Should().BeTrue();
    }

    [Fact]
    public void Parses_a_flow_sequence()
    {
        var header = FrontMatter.Parse("---\ntags: [auth, \"security\"]\n---\n");

        header.Find("tags")!.Items.Should().Equal("auth", "security");
    }

    [Fact]
    public void Flattens_nested_mappings_into_dotted_keys()
    {
        var header = FrontMatter.Parse("---\nrun:\n  model: opus\n  id: 42\n---\n");

        header.Find("run.model")!.Value.Should().Be("opus");
        header.Find("run.id")!.Value.Should().Be("42");
        // The parent holds no value of its own but is not an unfilled field.
        header.Find("run")!.IsMapping.Should().BeTrue();
        header.Find("run")!.HasValue.Should().BeTrue();
    }

    [Fact]
    public void Marks_every_ancestor_of_a_deeply_nested_key_as_a_mapping()
    {
        var header = FrontMatter.Parse("---\nrun:\n  tool:\n    name: spectacle\n---\n");

        header.Find("run.tool.name")!.Value.Should().Be("spectacle");
        header.Find("run.tool")!.IsMapping.Should().BeTrue();
        header.Find("run")!.IsMapping.Should().BeTrue();
    }

    [Fact]
    public void A_blank_value_is_not_a_filled_in_key()
    {
        var header = FrontMatter.Parse("---\nstatus:\ntitle: Auth\n---\n");

        header.Find("status")!.HasValue.Should().BeFalse();
        header.Find("title")!.HasValue.Should().BeTrue();
    }

    [Fact]
    public void Skips_comments_and_blank_lines()
    {
        var header = FrontMatter.Parse("---\n# generated by the writer agent\n\ntitle: Auth\n---\n");

        header.Entries.Select(e => e.Key).Should().Equal("title");
    }

    [Fact]
    public void Ignores_a_prose_line_that_is_not_a_key()
    {
        // A URL's colon is not followed by whitespace, so it is never read as a key separator.
        var header = FrontMatter.Parse("---\nhttps://example.com/docs\ntitle: Auth\n---\n");

        header.Entries.Select(e => e.Key).Should().Equal("title");
    }

    [Fact]
    public void Reports_an_unclosed_header()
    {
        var header = FrontMatter.Parse("---\ntitle: Auth\n\n# Body\n");

        header.Present.Should().BeTrue();
        header.Closed.Should().BeFalse();
    }

    [Fact]
    public void Closes_on_a_yaml_document_end_marker()
    {
        FrontMatter.Parse("---\ntitle: Auth\n...\n").Closed.Should().BeTrue();
    }

    [Fact]
    public void Tolerates_a_byte_order_mark_before_the_fence()
    {
        FrontMatter.Parse("\uFEFF---\ntitle: Auth\n---\n").Present.Should().BeTrue();
    }

    [Fact]
    public void Metadata_flattens_to_display_pairs_in_source_order()
    {
        var header = FrontMatter.Parse("---\ntitle: Auth\ntags: [a, b]\nrun:\n  model: opus\n---\n");

        header.Metadata.Select(m => m.Key).Should().Equal("title", "tags", "run.model");
        header.Metadata.Select(m => m.Value).Should().Equal("Auth", "a, b", "opus");
    }

    [Fact]
    public void Strip_blanks_the_header_and_preserves_the_line_count()
    {
        const string source = "---\ntitle: Auth\n---\n\n# Body\n\nText.\n";
        var body = FrontMatter.Strip(source);

        body.Split('\n').Length.Should().Be(source.Split('\n').Length);
        body.Split('\n').Take(3).Should().AllSatisfy(l => l.Should().BeEmpty());
        // The body keeps its original line numbers, which is what lets a finding point at the
        // right line of the real file.
        body.Split('\n')[4].Should().Be("# Body");
    }

    [Fact]
    public void Strip_leaves_a_document_without_front_matter_untouched()
    {
        const string source = "# Body\n\nText.\n";
        FrontMatter.Strip(source).Should().Be(source);
    }

    [Fact]
    public void Strip_leaves_an_unclosed_header_untouched()
    {
        // There is no fence to bound, so blanking would swallow the document and hide every other
        // finding; the unclosed header is reported by its own rule instead.
        const string source = "---\ntitle: Auth\n\n# Body\n";
        FrontMatter.Strip(source).Should().Be(source);
    }

    [Fact]
    public void Strip_preserves_crlf_line_endings_in_the_body()
    {
        var body = FrontMatter.Strip("---\r\ntitle: Auth\r\n---\r\n\r\n# Body\r\n");

        body.Should().Contain("# Body\r\n");
    }

    [Fact]
    public void Split_returns_the_header_and_the_body_together()
    {
        var (header, body) = FrontMatter.Split("---\ntitle: Auth\n---\n\n# Body\n");

        header.Find("title")!.Value.Should().Be("Auth");
        body.Should().Contain("# Body").And.NotContain("title: Auth");
    }

    [Fact]
    public void Folds_a_folded_block_scalar_into_its_text()
    {
        var header = FrontMatter.Parse(
            "---\npurpose: >-\n  Collects reviewer feedback on the pipeline so a later\n  session can answer it.\n---\n");

        var purpose = header.Find("purpose")!;
        purpose.Value.Should().Be("Collects reviewer feedback on the pipeline so a later session can answer it.");
        purpose.Line.Should().Be(2);
        purpose.HasValue.Should().BeTrue();
    }

    [Fact]
    public void Keeps_the_line_breaks_of_a_literal_block_scalar()
    {
        var header = FrontMatter.Parse("---\nnotes: |\n  first line\n  second line\n---\n");

        header.Find("notes")!.Value.Should().Be("first line\nsecond line");
    }

    [Fact]
    public void A_blank_line_does_not_end_a_block_scalar()
    {
        var header = FrontMatter.Parse(
            "---\nhistory: >\n  The first paragraph.\n\n  The second paragraph.\nstatus: draft\n---\n");

        header.Find("history")!.Value.Should().Be("The first paragraph.\nThe second paragraph.");
        header.Find("status")!.Value.Should().Be("draft");
    }

    [Fact]
    public void Prose_inside_a_block_scalar_is_never_read_as_a_key()
    {
        // The body of a block scalar is text, so a colon or a dash in it is punctuation. Reading it
        // as structure invented metadata the document never declared.
        var header = FrontMatter.Parse(
            "---\npurpose: |\n  Line one of the purpose.\n  note: this line is prose, not a key.\n  - and this is prose too\nstatus: draft\n---\n");

        header.Entries.Select(e => e.Key).Should().Equal("purpose", "status");
        header.Find("purpose")!.Value.Should()
            .Contain("note: this line is prose").And.Contain("- and this is prose too");
        header.Find("purpose")!.Items.Should().BeEmpty();
    }

    [Fact]
    public void An_empty_block_scalar_is_not_a_filled_in_key()
    {
        var header = FrontMatter.Parse("---\npurpose: >-\nstatus: draft\n---\n");

        header.Find("purpose")!.Value.Should().BeEmpty();
        header.Find("purpose")!.HasValue.Should().BeFalse();
    }

    [Fact]
    public void Reads_a_block_scalar_with_an_explicit_indent_indicator()
    {
        var header = FrontMatter.Parse("---\npurpose: |2-\n  the text\n---\n");

        header.Find("purpose")!.Value.Should().Be("the text");
    }

    [Fact]
    public void Folds_the_continuation_lines_of_a_plain_scalar()
    {
        var header = FrontMatter.Parse(
            "---\npurpose: Collects reviewer feedback so a later\n  session can answer it.\n---\n");

        header.Find("purpose")!.Value.Should().Be("Collects reviewer feedback so a later session can answer it.");
    }

    [Fact]
    public void Folds_the_continuation_lines_of_a_sequence_item()
    {
        var header = FrontMatter.Parse(
            "---\nconstraints:\n  - Question headings are stable anchors - never reword\n    them.\n  - Answers are never deleted.\n---\n");

        header.Find("constraints")!.Items.Should().Equal(
            "Question headings are stable anchors - never reword them.",
            "Answers are never deleted.");
    }

    [Fact]
    public void Reads_a_sequence_of_mappings_as_one_item_per_element()
    {
        // The shape the artifact-context policy prescribes. An element's fields belong to that
        // element, not to a dotted path under the sequence key, where the second element would
        // overwrite the first and every decision text would vanish.
        var header = FrontMatter.Parse(
            "---\ndecisions:\n  - decision: Use a 30-second retry delay.\n    reason: Telemetry showed 10 seconds was too aggressive.\n  - decision: Anchor answers under their question heading.\n    reason: The heading is the stable identity.\n---\n");

        header.Entries.Select(e => e.Key).Should().Equal("decisions");
        header.Find("decisions")!.Items.Should().Equal(
            "decision: Use a 30-second retry delay.; reason: Telemetry showed 10 seconds was too aggressive.",
            "decision: Anchor answers under their question heading.; reason: The heading is the stable identity.");
    }

    [Fact]
    public void Reads_a_block_scalar_field_of_a_sequence_element()
    {
        var header = FrontMatter.Parse(
            "---\ndecisions:\n  - decision: >-\n      Use a 30-second retry delay.\n    reason: Telemetry.\n---\n");

        header.Find("decisions")!.Items.Should().Equal(
            "decision: Use a 30-second retry delay.; reason: Telemetry.");
    }

    [Fact]
    public void Reads_a_block_scalar_nested_under_a_mapping()
    {
        var header = FrontMatter.Parse(
            "---\nartifact_context:\n  purpose: >-\n    What this is for.\n  history: >-\n    How it got here.\n---\n");

        header.Find("artifact_context.purpose")!.Value.Should().Be("What this is for.");
        header.Find("artifact_context.history")!.Value.Should().Be("How it got here.");
        header.Find("artifact_context")!.IsMapping.Should().BeTrue();
    }

    [Fact]
    public void An_unindented_body_line_ends_a_block_scalar_in_an_unclosed_header()
    {
        // There is no fence to stop at, so the scalar runs until a line at the key's own indent.
        // The unclosed header is reported by its own rule; what matters here is that the value is
        // the scalar's text and not the rest of the document.
        var header = FrontMatter.Parse("---\npurpose: >-\n  the text\n\n# Body\n\nText.\n");

        header.Closed.Should().BeFalse();
        header.Find("purpose")!.Value.Should().Be("the text");
    }

    [Fact]
    public void Metadata_renders_a_multi_line_value_on_one_line()
    {
        // A display pair lands in a Markdown brief and in one-line-per-key listings, so a literal
        // scalar's breaks would split the line it sits on. The entry itself keeps them.
        var header = FrontMatter.Parse("---\nnotes: |\n  first line\n  second line\n---\n");

        header.Metadata.Single().Value.Should().Be("first line second line");
        header.Find("notes")!.Value.Should().Be("first line\nsecond line");
    }
}
